"""initial food items and user_food_items tables

Revision ID: 0000_initial
Revises:
Create Date: 2025-11-04 00:00:00.000000
"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from uuid import uuid4

# revision identifiers, used by Alembic.
revision = "0000_initial"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "food_items",
        sa.Column("id", sa.Uuid(), nullable=False, server_default=sa.text("uuid_generate_v4()")),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("price", sa.Float(), nullable=False),
        sa.Column("category", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id", name="pk_food_items"),
    )

    op.create_table(
        "user_food_item",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("food_item_id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False, server_default=sa.text("now()")),
        sa.ForeignKeyConstraint(
            ["food_item_id"], ["food_items.id"], name="fk_user_food_item_food_item"
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], name="fk_user_food_item_user"),
        sa.PrimaryKeyConstraint("user_id", "food_item_id", name="pk_user_food_item"),
        sa.UniqueConstraint("user_id", "food_item_id", name="uq_user_food_item"),
    )
    # ### end Alembic commands ###

    # Enable uuid-ossp extension for uuid_generate_v4() if using PostgreSQL
    bind = op.get_bind()
    if bind.dialect.name == "postgresql":
        op.execute('CREATE EXTENSION IF NOT EXISTS "uuid-ossp"')


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user_food_item")
    op.drop_table("food_items")
    # ### end Alembic commands ###

    # Clean up uuid-ossp extension if using PostgreSQL
    bind = op.get_bind()
    if bind.dialect.name == "postgresql":
        op.execute('DROP EXTENSION IF EXISTS "uuid-ossp"')
