AWSTemplateFormatVersion: "2010-09-09"
Description: "EC2 Instance"
Resources:
  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-0435fcf800fb5418d
      InstanceType: t2.micro
