AWSTemplateFormatVersion: "2010-09-09"
Description: "EC2 Instance"

Parameters:
  KeyName:
    Description: Name of an existing EC2 KeyPair
    Type: AWS::EC2::KeyPair::ec2-key

Resources:
  MySecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow SSH
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0

  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-0435fcf800fb5418d
      InstanceType: t2.micro
      SecurityGroupIds:
        - Ref: MySecurityGroup
      KeyName: !Ref KeyName
